version: '2.1'
services:
    #NGINX Proxy and Web Server     
    nginx:
        container_name: nginx
        hostname: nginx
        build: ./
        ports:
            - 9999:9000     # Workshop Lab Guide
        restart: always #  - if you want persistent through host reboots
        